FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    libxml2-dev libxslt-dev libsuitesparse-dev \
    pkg-config cmake ninja-build gfortran swig gcc g++ \
    && rm -rf /var/lib/apt/lists/*

# Use 'app' instead of 'spark'
WORKDIR /home/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the CONTENTS of your local pyfrbus folder into the image
# This ensures the structure is /home/app/pyfrbus/load_data.py
COPY pyfrbus/ /home/app/pyfrbus/

# Set PYTHONPATH so 'import pyfrbus' works from /home/app
ENV PYTHONPATH="/home/app"