version: '3.8'

services:
  engine:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: pyfrbus-engine:latest
    container_name: macro_engine
    volumes:
      # Map local folders to container folders
      # This allows you to see results immediately on your host machine
      - ./results:/home/app/results
      - ./debug_data:/home/app/debug_data
      - ./data:/home/app/data
    environment:
      - PYTHONPATH=/home/app
    # The command to run your specific script
    command: python src/engine.py
