import pytest
import numpy as np
import os
import pandas as pd
from unittest.mock import patch, MagicMock
from src.engine import run_backtest_chunk, solve_system

# --- FIXTURES ---

@pytest.fixture
def mock_tealbook_data():
    """Creates a fake Tealbook dataframe for testing."""
    return pd.DataFrame({
        'DATE': ['2004-01-01', '2005-01-01', '2024-01-01'],
        'F0': [5.5, 5.2, 3.8], # 'F0' is the typical Phil Fed column for Nowcast
        'OTHER': [0, 0, 0]
    })

# --- TESTS ---

def test_solve_system_returns_tuple():
    """Verify the solver + timer decorator return (result, time)."""
    from scipy.sparse import eye
    A = eye(5).tocsc()
    b = np.ones(5)
    
    result, duration = solve_system(A, b)
    
    assert len(result) == 5
    assert isinstance(duration, float)
    assert np.allclose(result, b)

@patch('src.engine.pd.read_csv')
@patch('src.engine.os.path.exists')
def test_engine_uses_tealbook_value(mock_exists, mock_read_csv, mock_tealbook_data):
    """
    Verify the engine correctly filters the CSV for the target year
    and uses that value in the solver.
    """
    mock_exists.return_value = True
    mock_read_csv.return_value = mock_tealbook_data
    
    # Run for Task 0 (2004)
    # Inside engine.py, it should find 5.5 in our mock data
    run_backtest_chunk(0)
    
    # Check the output CSV generated by the engine
    output_path = "/home/spark/results/backtest_2004.csv"
    assert os.path.exists(output_path)
    
    output_df = pd.read_csv(output_path)
    assert output_df['target_unemployment'].iloc[0] == 5.5
    assert output_df['year'].iloc[0] == 2004

@patch('src.engine.os.path.exists')
def test_engine_fallback_when_data_missing(mock_exists):
    """Ensure the engine defaults to 5.0% if no data file exists."""
    mock_exists.return_value = False
    
    run_backtest_chunk(1) # 2005
    
    output_df = pd.read_csv("/home/spark/results/backtest_2005.csv")
    assert output_df['target_unemployment'].iloc[0] == 5.0

def test_directory_creation_logic(tmp_path, monkeypatch):
    """Verify results directory is handled correctly in isolation."""
    # This prevents the test from writing to your actual /home/spark/results
    test_results_dir = tmp_path / "results"
    monkeypatch.setattr("src.engine.os.makedirs", lambda path, exist_ok: test_results_dir.mkdir(parents=True, exist_ok=True))
    
    # Patch the save path inside engine.py for this specific test
    with patch('src.engine.os.path.join', return_value=str(test_results_dir / "test.csv")):
        run_backtest_chunk(0)
        assert test_results_dir.exists()