import pandas as pd
from pyfrbus.frbus import Frbus
from pyfrbus.load_data import load_data
import sympy
import builtins
import os
import subprocess

# Inject Derivative into the global builtins so the lambdas in 
# pyfrbus/run_jac.py can see it regardless of import path issues.
builtins.Derivative = sympy.Derivative
builtins.symbols = sympy.symbols
builtins.exp = sympy.exp # Common in FRB/US models
builtins.log = sympy.log    


# 1. SETUP
os.makedirs("results", exist_ok=True)
os.makedirs("external_data", exist_ok=True)

# 2. LOAD & ROUND DATA
# Rounding to 6 decimal places prevents long floats like 4.52193548387097
# from being generated by the solver's internal calculations.
data = load_data("data/LONGBASE.TXT")
data = data.round(6) 
data.columns = [str(c).strip().lower() for c in data.columns]

# 3. PATCH KNOWN MISSING VARS
if 'dmptmax' not in data.columns:
    data['dmptmax'] = 0.0

# 4. LOAD MODEL
frbus = Frbus("models/model.xml")

# 5. INITIALIZE & SOLVE
start, end = "2023Q1", "2030Q4"
try:
    print("🚀 Running solve with Rounded Data Precision...")
    baseline_with_adds = frbus.init_trac(start, end, data)
    
    # We use the standard solve. If it fails, the error message 
    # will now show a rounded number, confirming the theory.
    sim = frbus.solve(start, end, baseline_with_adds)
    
    sim.to_csv("results/output.csv")
    print("✅ Success! The precision-drift has been corrected.")
except Exception as e:
    print(f"❌ Failure: {e}")