name: 'macro_ops'
version: '1.0.0'
config-version: 2

# This must match the name in your profiles.yml
profile: 'macro_ops'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "INSTALL parquet;"
  - "LOAD parquet;"
  # REMOVE the CREATE SECRET line entirely

models:
  macro_ops:
    # This applies the 'view' setting to everything in the models/ folder
    +materialized: table

vars:
  raw_data_path: "gs://macro-engine-warehouse-macroflow-486515/raw"
