macro_ops:
  outputs:
    dev:
      type: duckdb
      path: /app/data/macro_warehouse.duckdb  # This writes to your Mac's ./data folder
      extensions:
        - httpfs
        - parquet
  target: dev